[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_VERSION = "20", NODE_ENV = "production", NPM_FLAGS = "--legacy-peer-deps" }
